# JSON library for Terumi.
# The latest version may be found at https://github.com/terumi-project/json

name = 'json'
author = 'SirJosh3917'
description = 'JSON library written in Terumi'

[[snapshot]]
version = '0.0.2'
path = ''
git_url = 'https://github.com/terumi-project/json'
branch = 'master'
commit = '6499d0858885990183d657413be04c53837f949b'

[[snapshot]]
version = '0.0.1'
path = ''
git_url = 'https://github.com/terumi-project/json'
branch = 'master'
commit = '0a26c21508cf9fab22469d29cc570109706964d0'
