# This is the terumi standard library's package.
# Use it as the primary example of what a package should look like

# Simple metadata
name = 'terumi'
author = 'SirJosh3917'
description = 'The standard terumi library'

# Snapshots go here
# The most recent snapshot should be the first one,
# with all subsequent (and older) versions being near the end.

[[snapshot]]
project = 'terumi'
version = '0.0.1'
git_url = 'https://github.com/terumi-project/terumi_std'
branch = 'master'
commit = '897761b22a80d3e11762830f0da1227ab8553e0b'